# Neural network
batch_size: 16
dropout: 0.1
input_size: 3
hidden_sizes: [128, 128]
output_size: 1

# Learning
num_rounds: 4 #20 #10
do_cross_val: False
num_cross_val_folds: 2 #5 #3
num_epochs: 20 #50 #20
test_size: 0.2
learning_rate: 0.0001
binarization_threshold: 0.4

# Strategy
fraction_fit: 1.0         # fraction of clients that will be sampled per round
fraction_evaluate: 1.0    # fraction of clients sampled for evaluation
min_fit_clients: 2        # minimum of clients in a training round
min_evaluate_clients: 2   # minimum of clients for evaluation
min_available_clients: 2  # minimum of clients to stablish connection
proximal_mu: 0.01         # regularization strength
