# Neural network
batch_size: 16
dropout: 0.1
hidden_sizes: [128, 128]

# Learning
num_rounds: 20
num_cross_val_folds_round: 5
num_epochs: 50
test_size: 0.2
learning_rate: 0.0001
binarization_threshold: 0.4